collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2670251
color:
  saturation: 0.5573477
  brandStrength: 0.9426523
  lightness: 0.05555556
  brandColors:
    - '#141414'
    - '#56A7D0'
    - '#CFD7D8'
    - '#88CEFD'
    - '#A35C27'
  rhythmicContrast: 0.9354839
layout_spectrum: 0.2132616
name: WANDERLOST
