title: 'Solvignant in Nature '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7401434
  brandStrength: 0.8853046
  lightness: 0.1326165
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#E0C725'
    - '#A38344'
    - '#6C572D'
  rhythmicContrast: 0.2222222
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: 'Wanderlost '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0866
layout_spectrum: 0
