collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.8763441
  lightness: 0.7526882
  brandColors:
    - '#040302'
    - '#202E43'
    - '#5D6D88'
    - '#8892A3'
    - '#887766'
  rhythmicContrast: 0.1648746
typography_spectrum: 0.5286738
layout_spectrum: 0.4892473
name: WANDERLOST
