title: 'Solvignant in Nature '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.734767
  brandStrength: 0.875
  lightness: 0.625
  brandColors:
    - '#000000'
    - '#f0efed'
    - '#483932'
    - '#917661'
    - '#5890ff'
  rhythmicContrast: 0.5394265
cta:
  bucket: null
  version: null
  domain: null
name: 'Wanderlost '
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0866
layout_spectrum: 0.8243728
