collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7225969
  brandStrength: 0.7352445
  lightness: 0.8001686
  brandColors:
    - '#020300'
    - '#FDFDE7'
    - '#BDC6BC'
    - '#414B53'
    - '#5D6F76'
  rhythmicContrast: 0.6129848
typography_spectrum: 0.9160401
layout_spectrum: 0.2032041
name: WANDERLOST
