collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2867384
color:
  saturation: 0.5053763
  brandStrength: 0.9265233
  lightness: 0.5340502
  brandColors:
    - '#16170C'
    - '#B4B4B4'
    - '#FFFFFF'
    - '#6E6D6E'
    - '#BD9A77'
  rhythmicContrast: 0.2903226
layout_spectrum: 0.08178752
name: WANDERLOST
