name: 'Wanderlost '
favicon: null
layout_spectrum: 0.39354
typography_spectrum: 0.3403
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Solvagant by Nature '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fafff7'
    - '#030300'
    - '#4a596a'
    - '#ddc6a8'
    - '#ac6732'
  brandStrength: 0.9375
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
