name: 'Wanderlost '
favicon: null
layout_spectrum: 0.11359
typography_spectrum: 0.27748
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ' Solvagant by nature, I Wander alone.   With Nothing behind me, everything ahead of me, as is ever so on the road.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefd'
    - '#1b1919'
    - '#67686e'
    - '#fd9f3c'
    - '#cfbcaa'
  brandStrength: 0.9375
  lightness: 0.625
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
