name: WANDERLOST
favicon: null
layout_spectrum: 0.20752
typography_spectrum: 0.11789
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Those that Wander are not lost
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#004E87'
    - '#843701'
    - '#9CAAAD'
    - '#5D5D5A'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
