collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8405018
  brandStrength: 0.8763441
  lightness: 0.5179211
  brandColors:
    - '#88CEFD'
    - '#171616'
    - '#5C391F'
    - '#CFD7D8'
    - '#A35C27'
  rhythmicContrast: 0.4569893
typography_spectrum: 0.5286738
layout_spectrum: 0.2383513
name: WANDERLOST
