collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 1
color:
  saturation: 0.1433692
  brandStrength: 0.9265233
  lightness: 0.6021506
  brandColors:
    - '#281F0C'
    - '#655330'
    - '#8F784C'
    - '#B29B6F'
    - '#FCFCFA'
  rhythmicContrast: 0.2258064
layout_spectrum: 0.1326165
name: WANDERLOST
