collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2670251
color:
  saturation: 0.4317043
  brandStrength: 0.8827993
  lightness: 0.8895447
  brandColors:
    - '#141414'
    - '#56A7D0'
    - '#CFD7D8'
    - '#88CEFD'
    - '#A35C27'
  rhythmicContrast: 0.1203008
layout_spectrum: 0.2092732
name: WANDERLOST
