collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2588533
  brandStrength: 0.5708263
  lightness: 0.4637437
  brandColors:
    - '#FEFEFE'
    - '#303030'
    - '#5D88BD'
    - '#BEBCBD'
    - '#0080DF'
  rhythmicContrast: 0.8549747
typography_spectrum: 0.2908938
layout_spectrum: 1
name: Wanderlost
