collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 1
color:
  saturation: 0.6218638
  brandStrength: 0.9265233
  lightness: 0.6738351
  brandColors:
    - '#FFFBF2'
    - '#6E5339'
    - '#99B5D9'
    - '#D8AD91'
    - '#C67F02'
  rhythmicContrast: 0.5143369
layout_spectrum: 0.1326165
name: WANDERLOST
