name: WANDERLOST
favicon: null
layout_spectrum: 0.69962
typography_spectrum: 0.34601
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: One who's traveled the roads knows where holes are deepest
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefd'
    - '#1b1919'
    - '#67686e'
    - '#fd9f3c'
    - '#cfbcaa'
  brandStrength: 0.75
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
