collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2670251
color:
  saturation: 0.8781362
  brandStrength: 0.8691756
  lightness: 0.1362007
  brandColors:
    - '#141414'
    - '#56A7D0'
    - '#CFD7D8'
    - '#88CEFD'
    - '#A35C27'
  rhythmicContrast: 0.5179211
layout_spectrum: 0.2132616
name: WANDERLOST
