collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5092749
  brandStrength: 0.732715
  lightness: 0.7938597
  brandColors:
    - '#1E2915'
    - '#89ACCE'
    - '#657688'
    - '#FFD0A3'
    - '#914220'
  rhythmicContrast: 0.3452381
typography_spectrum: 0.8988196
layout_spectrum: 0
name: WANDERLOST
