name: 'Wanderlost '
favicon: null
layout_spectrum: 0.64911
typography_spectrum: 0.64173
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: 'Solvignant in Nature '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f0efed'
    - '#483932'
    - '#917661'
    - '#5890ff'
  brandStrength: 0.9375
  lightness: 0.8125
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
