collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.8978494
color:
  saturation: 0.0734767
  brandStrength: 0.9247312
  lightness: 0.5017921
  brandColors:
    - '#88CEFD'
    - '#171616'
    - '#5C391F'
    - '#CFD7D8'
    - '#A35C27'
  rhythmicContrast: 0.1362007
layout_spectrum: 0.327957
name: WANDERLOST
