collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.9160401
color:
  saturation: 0.7225969
  brandStrength: 0.732715
  rhythmicContrast: 0.5344611
  brandColors:
    - '#1E2915'
    - '#89ACCE'
    - '#657688'
    - '#FFD0A3'
    - '#914220'
  lightness: 0.737774
layout_spectrum: 0.1838111
name: WANDERLOST
