collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8001686
color:
  saturation: 0.5952783
  brandStrength: 0.9247312
  lightness: 0.2951096
  brandColors:
    - '#88CEFD'
    - '#171616'
    - '#5C391F'
    - '#CFD7D8'
    - '#A35C27'
  rhythmicContrast: 0.2141653
layout_spectrum: 0
name: WANDERLOST
