collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6559139
  brandStrength: 0.8763441
  lightness: 0.6505376
  brandColors:
    - '#201E16'
    - '#FFFFFF'
    - '#535D5C'
    - '#BE8742'
    - '#BDBDBD'
  rhythmicContrast: 0.2956989
typography_spectrum: 0.2867384
layout_spectrum: 0.4892473
name: WANDERLOST
