collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.3853047
  brandStrength: 0.8763441
  lightness: 0.5340502
  brandColors:
    - '#FFFFFF'
    - '#F14A03'
    - '#02B1C9'
    - '#654130'
    - '#0E0201'
  rhythmicContrast: 0.2956989
typography_spectrum: 0.2867384
layout_spectrum: 0.08178752
name: WANDERLOST
