collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.5657673
  brandStrength: 1
  lightness: 0.8305228
  brandColors:
    - '#423101'
    - '#8B95A3'
    - '#CDDCFE'
    - '#6E98FC'
    - '#C59205'
  rhythmicContrast: 0.3549747
typography_spectrum: 1
layout_spectrum: 0.4890388
name: WANDERLOST
