collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 1
color:
  saturation: 0.5615515
  brandStrength: 0.9265233
  lightness: 0.6021506
  brandColors:
    - '#1E2715'
    - '#5D7991'
    - '#FFFFFF'
    - '#FFFFA3'
    - '#F16E1E'
  rhythmicContrast: 0.6652614
layout_spectrum: 0.1326165
name: WANDERLOST
