collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6058897
  brandStrength: 0.7969925
  lightness: 0.537594
  brandColors:
    - '#1E2915'
    - '#89ACCE'
    - '#657688'
    - '#FFD0A3'
    - '#914220'
  rhythmicContrast: 0.3452381
typography_spectrum: 0.7222222
layout_spectrum: 0.3746867
name: WANDERLOST
