name: 'Wanderlost '
favicon: null
layout_spectrum: 0.20104
typography_spectrum: 0.79079
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: ' Solvagant by nature, I wander alone.   With nothing behind me, everything ahead of me, as is ever so on the road.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b250a'
    - '#fffeca'
    - '#b3791a'
    - '#ffd67c'
    - '#afa566'
  brandStrength: 1
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
