collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8794267
  brandStrength: 0.846543
  lightness: 0.8102867
  brandColors:
    - '#1D2842'
    - '#FBC630'
    - '#423001'
    - '#775C01'
    - '#A48802'
  rhythmicContrast: 0.1399663
typography_spectrum: 0
layout_spectrum: 0
name: WANDERLOST
