color:
  saturation: 0.7249373
  brandStrength: 0.8746867
  rhythmicContrast: 0.2042606
  brandColors:
    - '#1E2915'
    - '#89ACCE'
    - '#657688'
    - '#FFD0A3'
    - '#914220'
  lightness: 0.6754386
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
layout_spectrum: 0.8928571
typography_spectrum: 0.3214286
name: WANDERLOST
