collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2204301
  brandStrength: 0.9426523
  lightness: 0.08602151
  brandColors:
    - '#000000'
    - '#004E87'
    - '#843701'
    - '#9CAAAD'
    - '#5D5D5A'
  rhythmicContrast: 0.7921147
typography_spectrum: 0.9050179
layout_spectrum: 0.6487455
name: WANDERLOST
