collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5394265
color:
  saturation: 0.688172
  brandStrength: 0.9247312
  lightness: 0.4641577
  brandColors:
    - '#88CEFD'
    - '#171616'
    - '#5C391F'
    - '#CFD7D8'
    - '#A35C27'
  rhythmicContrast: 0.2616487
layout_spectrum: 0.4767025
name: WANDERLOST
