name: WANDERLOST
favicon: null
layout_spectrum: 0.07224
typography_spectrum: 0.43345
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Only he that has traveled the road knows where the holes are deep
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#004E87'
    - '#843701'
    - '#9CAAAD'
    - '#5D5D5A'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
