collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5394265
  brandStrength: 0.9247312
  lightness: 0.5232975
  brandColors:
    - '#88CEFD'
    - '#171616'
    - '#5C391F'
    - '#CFD7D8'
    - '#A35C27'
  rhythmicContrast: 0.265233
typography_spectrum: 0.2759857
layout_spectrum: 0.281362
name: WANDERLOST
