collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7078853
  brandStrength: 0.7329749
  lightness: 0.3405018
  brandColors:
    - '#88CEFD'
    - '#171616'
    - '#5C391F'
    - '#CFD7D8'
    - '#A35C27'
  rhythmicContrast: 0.1845878
typography_spectrum: 0.9050179
layout_spectrum: 0.2383513
name: WANDERLOST
