collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.7741935
  brandStrength: 0.9247312
  lightness: 0.7293907
  brandColors:
    - '#88CEFD'
    - '#171616'
    - '#5C391F'
    - '#CFD7D8'
    - '#A35C27'
  rhythmicContrast: 0.1200717
typography_spectrum: 0.0734767
layout_spectrum: 0.1111111
name: WANDERLOST
