collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2908938
color:
  saturation: 0.7596965
  brandStrength: 1
  lightness: 0.3625633
  brandColors:
    - '#201F26'
    - '#C5C7CF'
    - '#020202'
    - '#534C42'
    - '#5C758F'
  rhythmicContrast: 0.4333895
layout_spectrum: 0.3777403
name: Wanderlost
