collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.8387097
  brandStrength: 0.9247312
  lightness: 0.5681003
  brandColors:
    - '#88CEFD'
    - '#171616'
    - '#5C391F'
    - '#CFD7D8'
    - '#A35C27'
  rhythmicContrast: 0.2419355
typography_spectrum: 0.1917563
layout_spectrum: 0.390681
name: WANDERLOST
