collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.8507589
color:
  saturation: 0.8642496
  brandStrength: 0.708263
  lightness: 0.7706577
  brandColors:
    - '#060606'
    - '#FFA200'
    - '#2D2D2D'
    - '#C67E00'
    - '#654001'
  rhythmicContrast: 0.2099494
layout_spectrum: 0
name: WANDERLOST
