collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1523297
  brandStrength: 0.9265233
  lightness: 0.6523297
  brandColors:
    - '#201E16'
    - '#FFFFFF'
    - '#535D5C'
    - '#BE8742'
    - '#BDBDBD'
  rhythmicContrast: 0.2795699
typography_spectrum: 1
layout_spectrum: 0.1326165
name: WANDERLOST
