collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 1
color:
  saturation: 0.8752108
  brandStrength: 0.8920742
  lightness: 0.6770658
  brandColors:
    - '#0C447E'
    - '#161616'
    - '#4C666D'
    - '#7F9292'
    - '#BEB2A3'
  rhythmicContrast: 0.3212479
layout_spectrum: 0
name: WANDERLOST
