collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1415771
  brandStrength: 0.9265233
  lightness: 0.8297491
  brandColors:
    - '#FB6C13'
    - '#421C04'
    - '#F2F2F2'
    - '#B89077'
    - '#9A420B'
  rhythmicContrast: 0.2401434
typography_spectrum: 1
layout_spectrum: 0.1326165
name: WANDERLOST
