collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6296992
  brandStrength: 0.7969925
  lightness: 0.6200717
  brandColors:
    - '#1E2915'
    - '#89ACCE'
    - '#657688'
    - '#FFD0A3'
    - '#914220'
  rhythmicContrast: 0.5413534
typography_spectrum: 0.7222222
layout_spectrum: 0.8151629
name: WANDERLOST
