collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9013491
  brandStrength: 0.8827993
  lightness: 0.3473862
  brandColors:
    - '#141414'
    - '#56A7D0'
    - '#CFD7D8'
    - '#88CEFD'
    - '#A35C27'
  rhythmicContrast: 0.1424958
typography_spectrum: 0.2670251
layout_spectrum: 0.07841484
name: WANDERLOST
