collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.9013491
color:
  saturation: 0.6323777
  brandStrength: 0.9247312
  rhythmicContrast: 0.2141653
  brandColors:
    - '#88CEFD'
    - '#171616'
    - '#5C391F'
    - '#CFD7D8'
    - '#A35C27'
  lightness: 0.4249578
layout_spectrum: 0
name: WANDERLOST
