collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.3577694
  brandStrength: 1
  lightness: 0.679198
  brandColors:
    - '#1E2915'
    - '#89ACCE'
    - '#657688'
    - '#FFD0A3'
    - '#914220'
  rhythmicContrast: 0.6146616
typography_spectrum: 0.6359649
layout_spectrum: 0.54198
name: Wanderlost
