collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.5286738
color:
  saturation: 1
  brandStrength: 0.8763441
  lightness: 0.7526882
  brandColors:
    - '#5C88BD'
    - '#303238'
    - '#010001'
    - '#BC9B91'
    - '#FFD789'
  rhythmicContrast: 0.1648746
layout_spectrum: 0.4892473
name: WANDERLOST
