title: 'Solvignant in Nature '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4605735
  brandStrength: 1
  lightness: 0.5053763
  brandColors:
    - '#000000'
    - '#f0efed'
    - '#483932'
    - '#917661'
    - '#5890ff'
  rhythmicContrast: 0.7222222
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Wanderlost '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0866
layout_spectrum: 0.5573477
