collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 1
color:
  saturation: 0.6812816
  brandStrength: 0.5699831
  lightness: 0.8305228
  brandColors:
    - '#423101'
    - '#8B95A3'
    - '#CDDCFE'
    - '#6E98FC'
    - '#C59205'
  rhythmicContrast: 0.2065767
layout_spectrum: 0
name: WANDERLOST
