collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2670251
color:
  saturation: 0.7445194
  brandStrength: 0.8827993
  lightness: 0.2630692
  brandColors:
    - '#141414'
    - '#56A7D0'
    - '#CFD7D8'
    - '#88CEFD'
    - '#A35C27'
  rhythmicContrast: 0.4494098
layout_spectrum: 0.3035413
name: WANDERLOST
