collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.4229391
  brandStrength: 0.9426523
  lightness: 0.3763441
  brandColors:
    - '#000000'
    - '#004E87'
    - '#843701'
    - '#9CAAAD'
    - '#5D5D5A'
  rhythmicContrast: 0.5609319
typography_spectrum: 0.9050179
layout_spectrum: 0.6397849
name: WANDERLOST
