collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.2655987
  brandStrength: 0.8827993
  lightness: 0.5615515
  brandColors:
    - '#141414'
    - '#D0D7D9'
    - '#A35B28'
    - '#55A6CF'
    - '#87CEFC'
  rhythmicContrast: 0.3288364
typography_spectrum: 0.2670251
layout_spectrum: 0.5168634
name: WANDERLOST
