name: WANDERLOST
favicon: null
layout_spectrum: 0.12928
typography_spectrum: 0.98859
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Only he that has traveled the road knows where the holes are deep
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a5a5a4'
    - '#000000'
    - '#e8e8e7'
    - '#124300'
    - '#655d42'
  brandStrength: 0.875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
