collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.9050179
color:
  saturation: 0.4892473
  brandStrength: 0.9426523
  lightness: 0.7060932
  brandColors:
    - '#000000'
    - '#004E87'
    - '#843701'
    - '#9CAAAD'
    - '#5D5D5A'
  rhythmicContrast: 0.1971326
layout_spectrum: 0.9910395
name: WANDERLOST
