collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.9050179
color:
  saturation: 0.9318997
  brandStrength: 0.9426523
  rhythmicContrast: 0.6935484
  brandColors:
    - '#000000'
    - '#004E87'
    - '#843701'
    - '#9CAAAD'
    - '#5D5D5A'
  lightness: 0.6845878
layout_spectrum: 0.4659498
name: WANDERLOST
