collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.9050179
color:
  saturation: 0.6379929
  brandStrength: 0.9426523
  lightness: 0.2885305
  brandColors:
    - '#000000'
    - '#004E87'
    - '#843701'
    - '#9CAAAD'
    - '#5D5D5A'
  rhythmicContrast: 0.6379929
layout_spectrum: 0.6397849
name: WANDERLOST
