collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.9197995
  brandStrength: 0.6578947
  lightness: 0.7938597
  brandColors:
    - '#1E2915'
    - '#89ACCE'
    - '#657688'
    - '#FFD0A3'
    - '#914220'
  rhythmicContrast: 0.3452381
typography_spectrum: 0.3665414
layout_spectrum: 0.7750627
name: WANDERLOST
