collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 1
  lightness: 0.1362007
  brandColors:
    - '#141414'
    - '#56A7D0'
    - '#CFD7D8'
    - '#88CEFD'
    - '#A35C27'
  rhythmicContrast: 0.3100359
typography_spectrum: 0.2670251
layout_spectrum: 0.2132616
name: WANDERLOST
