collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.08064516
  brandStrength: 0.9265233
  lightness: 0.6021506
  brandColors:
    - '#0C447E'
    - '#161616'
    - '#4C666D'
    - '#7F9292'
    - '#BEB2A3'
  rhythmicContrast: 0.4193548
typography_spectrum: 1
layout_spectrum: 0.1362007
name: WANDERLOST
