title: 'Solvignant in Nature '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3351254
  brandStrength: 0.8853046
  lightness: 0.2634408
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#04F4FD'
    - '#AAAAAA'
    - '#02A2A8'
  rhythmicContrast: 0.2222222
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: 'Wanderlost '
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0866
layout_spectrum: 0
