collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.2419355
  brandStrength: 0.9426523
  lightness: 0
  brandColors:
    - '#000000'
    - '#004E87'
    - '#843701'
    - '#9CAAAD'
    - '#5D5D5A'
  rhythmicContrast: 0.4121864
typography_spectrum: 0.9050179
layout_spectrum: 0.8960574
name: WANDERLOST
