collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2670251
color:
  saturation: 0.1408094
  brandStrength: 0.9247312
  lightness: 0.6686341
  brandColors:
    - '#141414'
    - '#D0D7D9'
    - '#A35B28'
    - '#55A6CF'
    - '#87CEFC'
  rhythmicContrast: 0.3288364
layout_spectrum: 0
name: WANDERLOST
