title: 'Solvignant in Nature '
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3351254
  brandStrength: 0.8853046
  lightness: 0.2634408
  brandColors:
    - '#7C3817'
    - '#687237'
    - '#C98F39'
    - '#007C7C'
    - '#CAF2E5'
  rhythmicContrast: 0.2222222
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
name: 'Wanderlost '
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0866
layout_spectrum: 0
