collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.1021505
color:
  saturation: 0.4874552
  brandStrength: 0.9247312
  rhythmicContrast: 0.2526882
  brandColors:
    - '#88CEFD'
    - '#171616'
    - '#5C391F'
    - '#CFD7D8'
    - '#A35C27'
  lightness: 0.2258064
layout_spectrum: 0.1523297
name: WANDERLOST
